#!/usr/bin/env python3
"""Run issue #54 against a disposable Forgejo 16.0.3 repository.

Uses only Python's standard library and Git. Two explicit pauses require a
real browser to create pending comments; API drafts are not a substitute.
See recordings/README.md for setup, invocation, and the recorded requests.
"""

from __future__ import annotations

import argparse
import base64
import json
import os
from pathlib import Path
import re
import subprocess
import urllib.error
import urllib.parse
import urllib.request


class NoRedirect(urllib.request.HTTPRedirectHandler):
    def redirect_request(self, req, fp, code, msg, headers, newurl):
        raise RuntimeError("redirect refused; use the server's direct base URL")


def scrub(value: object, secrets: tuple[str, ...]) -> object:
    """Preserve API shapes and identities while removing private strings."""
    if isinstance(value, dict):
        return {
            key: "<redacted>" if key.lower() in {
                "email", "token", "password", "cookie", "authorization",
                "set-cookie", "secret", "access_token",
            } else scrub(item, secrets)
            for key, item in value.items()
        }
    if isinstance(value, list):
        return [scrub(item, secrets) for item in value]
    if not isinstance(value, str):
        return value
    for secret in secrets:
        value = value.replace(secret, "<redacted>")
    value = re.sub(r"[\w.!#$%&'*+/=?^`{|}~-]+@[\w.-]+", "<redacted>", value)
    # Every URL authority is normalized, including documentation/error URLs.
    value = re.sub(r"(?i)(?:https?|ssh)://[^/\s\"<>]+", "http://127.0.0.1", value)
    return value


def validate_base_url(value: str) -> str:
    parsed = urllib.parse.urlsplit(value)
    if (parsed.scheme not in {"http", "https"} or not parsed.hostname
            or parsed.username or parsed.password or parsed.query
            or parsed.fragment or parsed.path not in {"", "/"}):
        raise ValueError("base URL must be an HTTP(S) origin without credentials")
    if parsed.scheme == "http" and parsed.hostname not in {"127.0.0.1", "::1"}:
        raise ValueError("plain HTTP is allowed only on loopback")
    return value.rstrip("/")


class Recorder:
    def __init__(self, base_url: str, tokens: dict[str, str], output: Path,
                 source_prefix: str = "../"):
        self.base_url = validate_base_url(base_url)
        self.tokens = tokens
        if any(not token or any(c.isspace() for c in token)
               for token in tokens.values()):
            raise ValueError("token files must each contain one non-empty token")
        self.output = output
        self.source_prefix = source_prefix
        self.output.mkdir(parents=True, exist_ok=False)
        self.rows: list[str] = []
        self.last_status: int | None = None
        self.opener = urllib.request.build_opener(
            urllib.request.ProxyHandler({}), NoRedirect())

    def save(self, experiment: str, name: str, request: dict,
             status: int, body: object) -> None:
        filename = f"{len(self.rows) + 1:03d}-{experiment.lower()}-{name}.json"
        record = scrub({"experiment": experiment, "request": request,
                        "response": {"status": status, "body": body}},
                       tuple(self.tokens.values()))
        (self.output / filename).write_text(
            json.dumps(record, indent=2, ensure_ascii=False) + "\n")
        self.rows.append(
            f"| [{filename}]({filename}) | {experiment} | {request['actor']} | "
            f"`{request['method']} {request['path']}` | {status} |")
        (self.output / "README.md").write_text(
            "# Forgejo 16.0.3 recordings\n\n"
            f"Generated by [record.py]({self.source_prefix}record.py). Each file contains the "
            "request body and complete response body, with secrets and email "
            "values redacted and URL origins normalized to `http://127.0.0.1`. "
            "Headers and browser cookies are never recorded. Array order, "
            "IDs, commit IDs, and timestamps are preserved. A null response "
            "body means an empty HTTP body. Setup and Git operations are "
            f"described in the [runbook]({self.source_prefix}README.md).\n\n"
            "| Recording | Experiment | Actor | Request | HTTP |\n"
            "| --- | --- | --- | --- | ---: |\n"
            + "\n".join(self.rows) + "\n")
        print(f"{filename}: {status}", flush=True)

    def request(self, experiment: str, name: str, method: str, path: str,
                actor: str = "author", body: dict | None = None,
                required: bool = False) -> object:
        headers = {"Accept": "application/json"}
        if actor != "anonymous":
            headers["Authorization"] = "token " + self.tokens[actor]
        data = None
        if body is not None:
            data = json.dumps(body).encode()
            headers["Content-Type"] = "application/json"
        request = urllib.request.Request(
            self.base_url + "/api/v1" + path, data=data,
            headers=headers, method=method)
        try:
            response = self.opener.open(request, timeout=30)
        except urllib.error.HTTPError as error:
            response = error
        with response:
            raw = response.read().decode()
            try:
                result = json.loads(raw) if raw else None
            except json.JSONDecodeError:
                result = raw
            status = response.status
        self.save(experiment, name, {"method": method, "path": path,
                  "actor": actor, "body": body}, status, result)
        self.last_status = status
        if required and not 200 <= status < 300:
            raise RuntimeError(f"{experiment}/{name} failed with HTTP {status}")
        return result


def run(args: argparse.Namespace) -> None:
    tokens = {name: Path(getattr(args, name + "_token_file")).read_text().strip()
              for name in ("author", "approver", "other")}
    recorder = Recorder(args.base_url, tokens, args.output)
    call = recorder.request
    version = call("SETUP", "version", "GET", "/version", "anonymous", required=True)
    if version != {"version": "16.0.3+gitea-1.22.0"}:
        raise RuntimeError("this experiment requires exactly Forgejo 16.0.3")
    for actor in tokens:
        user = call("SETUP", "user-" + actor, "GET", "/user", actor, required=True)
        if user["login"] != actor:
            raise RuntimeError(f"expected disposable login {actor}")
    call("SETUP", "settings", "GET", "/settings/api", "anonymous", required=True)
    repo = f"/repos/approver/{args.repository}"
    call("SETUP", "repository-absent", "GET", repo, "approver")
    if recorder.last_status != 404:
        raise RuntimeError("use a new repository name; existing repositories are refused")
    created = call("SETUP", "create-repository", "POST", "/user/repos", "approver",
         {"name": args.repository, "auto_init": True, "private": True,
          "default_branch": "main", "description": "Disposable issue 54 experiment"})
    if isinstance(created, dict) and created.get("message") == (
            "token does not have at least one of required scope(s): [write:user]"):
        input(f"SETUP: in the browser as approver, create private {args.repository} "
              "with main and an initial README. Then press Enter: ")
    elif not isinstance(created, dict) or "id" not in created:
        raise RuntimeError("repository creation failed; inspect the recording")
    # The browser setup pause is the only permitted source of this new repo.
    call("SETUP", "created-repository", "GET", repo, "approver", required=True)
    for actor, permission in (("author", "write"), ("other", "read")):
        call("SETUP", "collaborator-" + actor, "PUT",
             repo + "/collaborators/" + actor, "approver",
             {"permission": permission}, required=True)
    call("SETUP", "repository-author", "GET", repo, required=True)
    call("SETUP", "repository-other", "GET", repo, "other", required=True)

    # Tokens are supplied only in the child environment; no credential helper,
    # URL, argument, repository config, or Git output contains a token.
    git_env = os.environ.copy()
    basic = base64.b64encode(("author:" + tokens["author"]).encode()).decode()
    git_env.update({"GIT_CONFIG_COUNT": "1",
                    "GIT_CONFIG_KEY_0": f"http.{recorder.base_url}/.extraHeader",
                    "GIT_CONFIG_VALUE_0": "Authorization: Basic " + basic,
                    "GIT_TERMINAL_PROMPT": "0",
                    "GIT_AUTHOR_NAME": "author", "GIT_COMMITTER_NAME": "author",
                    "GIT_AUTHOR_EMAIL": "author" + "@example.invalid",
                    "GIT_COMMITTER_EMAIL": "author" + "@example.invalid"})
    args.git_workdir.mkdir(parents=True, exist_ok=False)
    git_log: list[dict] = []

    def git(*command: str) -> str:
        result = subprocess.run(
            ["git", "-c", "credential.helper=", "-c", "core.hooksPath=/dev/null",
             "-c", "commit.gpgsign=false", *command], cwd=args.git_workdir,
            env=git_env, capture_output=True, text=True, check=True)
        git_log.append({"command": list(command), "stdout": result.stdout,
                        "stderr": result.stderr, "exit_code": result.returncode})
        (args.output / "git-operations.json").write_text(json.dumps(
            scrub(git_log, (*tokens.values(), basic)), indent=2) + "\n")
        return result.stdout.strip()

    git("clone", recorder.base_url + f"/approver/{args.repository}.git", ".")
    for filename in ("alpha.txt", "beta.txt"):
        (args.git_workdir / filename).write_text(
            "".join(f"{filename} line {n:02d}\n" for n in range(1, 41)))
    git("add", "alpha.txt", "beta.txt")
    git("commit", "-m", "Seed two files for the review experiments")
    git("push", "origin", "main")
    git("checkout", "-b", "feature")
    for filename in ("alpha.txt", "beta.txt"):
        lines = (args.git_workdir / filename).read_text().splitlines()
        for number in (5, 25):
            lines[number - 1] += " changed"
        (args.git_workdir / filename).write_text("\n".join(lines) + "\n")
    (args.git_workdir / "new.txt").write_text("new line 1\nnew line 2\nnew line 3\nnew line 4\n")
    git("add", ".")
    git("commit", "-m", "Create separated hunks and a new file")
    git("push", "-u", "origin", "feature")
    head = git("rev-parse", "HEAD")
    diff = git("diff", "origin/main...HEAD")
    (args.output / "seed-diff.txt").write_text(diff + "\n")
    protection = {"rule_name": "main", "enable_push": True,
                  "required_approvals": 1, "block_on_rejected_reviews": True,
                  "dismiss_stale_approvals": True, "apply_to_admins": True}
    call("SETUP", "protect-main", "POST", repo + "/branch_protections",
         "approver", protection, required=True)
    call("SETUP", "protections-author", "GET", repo + "/branch_protections")
    pr = call("SETUP", "create-pr", "POST", repo + "/pulls", body={
        "head": "feature", "base": "main", "title": "Issue 54 API experiments",
        "body": "Disposable evidence only."}, required=True)
    pull = repo + f"/pulls/{pr['number']}"
    reviews = pull + "/reviews"
    call("SETUP", "request-review", "POST", pull + "/requested_reviewers",
         body={"reviewers": ["approver"]}, required=True)
    call("SETUP", "requested-reviews", "GET", reviews)
    call("SETUP", "pr-before-base-push", "GET", pull)
    git("checkout", "main")
    (args.git_workdir / "base-only.txt").write_text("Independent base update\n")
    git("add", "base-only.txt")
    git("commit", "-m", "Advance base without moving merge base")
    git("push", "origin", "main")
    git("checkout", "feature")
    call("SETUP", "pr-after-base-push", "GET", pull)

    def review(experiment: str, name: str, body: str, *, actor: str = "author",
               event: str = "COMMENT", commit: str = head,
               comments: list[dict] | None = None) -> dict:
        payload = {"body": body, "event": event, "commit_id": commit}
        if comments is not None:
            payload["comments"] = comments
        return call(experiment, name, "POST", reviews, actor, payload)

    first = review("E1", "own-comment", "E1 own COMMENT body", comments=[
        {"path": "alpha.txt", "new_position": 5, "body": "E1 alpha root"},
        {"path": "beta.txt", "new_position": 25, "body": "E1 beta root"}])
    for number in range(1, 4):
        call("E1", f"comments-order-{number}", "GET",
             reviews + f"/{first['id']}/comments")
    second = review("E2", "body-first", "E2 submitted body before roots")
    comment_path = reviews + f"/{second['id']}/comments"
    root = call("E2", "add-root", "POST", comment_path, body={
        "path": "alpha.txt", "new_position": 25, "body": "E2 root after submit"})
    if isinstance(root, dict) and "position" in root:
        for actor in ("author", "other"):
            call("E2", "reply-" + actor, "POST", comment_path, actor, {
                "path": root["path"], "new_position": root["position"],
                "body": "E2 reply from " + actor})
    call("E2", "comments", "GET", comment_path)
    third = review("E3", "invalid-anchors", "E3 invalid anchor rendering", comments=[
        {"path": "alpha.txt", "new_position": 15, "body": "E3 outside diff line 15"},
        {"path": "missing.txt", "new_position": 1, "body": "E3 missing path"}])
    call("E3", "comments", "GET", reviews + f"/{third['id']}/comments")
    review("E4", "bogus-commit", "E4 non-existent commit", commit="1" * 40)
    old_head = head
    (args.git_workdir / "new.txt").write_text(
        "new line 1\nnew line 2\nnew line 3\nnew line 4\nE4 head advance\n")
    git("add", "new.txt")
    git("commit", "-m", "Advance head before old-head review")
    git("push", "origin", "feature")
    head = git("rev-parse", "HEAD")
    call("E4", "pr-new-head", "GET", pull)
    review("E4", "old-head", "E4 valid earlier head", commit=old_head)
    call("E4", "reviews", "GET", reviews)
    ranged = review("E5", "range", "E5 range 2 through 4", commit=head, comments=[
        {"path": "new.txt", "new_position": 2, "extra_lines_count": 2,
         "body": "E5 range lines 2 through 4"}])
    call("E5", "comments", "GET", reviews + f"/{ranged['id']}/comments")
    print(f"Inspect E2/E3/E5 in {recorder.base_url}/approver/"
          f"{args.repository}/pulls/{pr['number']}")
    input("E6: as author, start a browser review with inline text "
          "'E6 UI draft absorbed'. Then press Enter: ")
    call("E6", "draft-before-submit", "GET", reviews)
    absorbed = review("E6", "body-only-submit", "E6 API body absorbs UI draft", commit=head)
    call("E6", "absorbed-comments", "GET", reviews + f"/{absorbed['id']}/comments")
    input("E6: as author, start a fresh browser review with inline text "
          "'E6 UI draft deleted'. Then press Enter: ")
    drafts = call("E6", "fresh-draft", "GET", reviews)
    pending = [row for row in drafts if row["state"] == "PENDING"]
    if len(pending) != 1:
        raise RuntimeError("expected exactly one author browser draft; inspect recorded evidence")
    call("E6", "draft-comments", "GET", reviews + f"/{pending[0]['id']}/comments")
    call("E6", "delete-draft", "DELETE", reviews + f"/{pending[0]['id']}")
    call("E6", "after-delete", "GET", reviews)
    for event in ("APPROVED", "REQUEST_CHANGES", "UNKNOWN_EVENT"):
        review("E8", event.lower(), "E8 own review " + event, event=event, commit=head)
    unknown = call("E8", "author-reviews", "GET", reviews)
    call("E8", "other-reviews", "GET", reviews, "other")
    for row in unknown:
        if row["state"] == "PENDING":
            call("E8", "delete-unknown-draft", "DELETE", reviews + f"/{row['id']}")

    merge_body = {"Do": "merge", "head_commit_id": head,
                  "delete_branch_after_merge": True}
    call("E7", "wrong-head", "POST", pull + "/merge",
         body={**merge_body, "head_commit_id": "2" * 40})
    call("E7", "no-approval", "POST", pull + "/merge", body=merge_body)
    review("E9", "approve-first", "E9 first approval", actor="approver",
           event="APPROVED", commit=head)
    call("E9", "after-first-approval", "GET", reviews)
    review("E9", "request-changes", "E9 changes requested", actor="approver",
           event="REQUEST_CHANGES", commit=head)
    call("E9", "after-request-changes", "GET", reviews)
    call("E9", "merge-after-request-changes", "POST", pull + "/merge", body=merge_body)
    (args.git_workdir / "new.txt").write_text(
        "new line 1\nnew line 2\nnew line 3\nnew line 4\nE9 changed after reviews\n")
    git("add", "new.txt")
    git("commit", "-m", "Advance head after approval and requested changes")
    git("push", "origin", "feature")
    head = git("rev-parse", "HEAD")
    merge_body["head_commit_id"] = head
    call("E9", "pr-after-push", "GET", pull)
    call("E9", "reviews-after-push", "GET", reviews)
    call("E9", "merge-after-push", "POST", pull + "/merge", body=merge_body)
    review("E9", "approve-again", "E9 approval of new head", actor="approver",
           event="APPROVED", commit=head)
    call("E9", "after-new-approval", "GET", reviews)
    call("E7", "merge-approved", "POST", pull + "/merge", body=merge_body)
    call("E7", "merged-pr", "GET", pull)
    call("E7", "deleted-branch", "GET", repo + "/branches/feature")
    call("E7", "delete-absent-branch", "DELETE", repo + "/branches/feature")
    call("FINAL", "issue-comment", "POST", repo + f"/issues/{pr['number']}/comments",
         body={"body": "Issue 54 experiment complete."})
    call("FINAL", "issue-comments", "GET", repo + f"/issues/{pr['number']}/comments")
    call("FINAL", "commit-status", "GET", repo + f"/commits/{head}/status")
    guard_probe(args)
    settled_reviews(args)
    print("API sequence complete. Record UI observations and remove "
          "the owned container and volume.")


def guard_probe(args: argparse.Namespace) -> None:
    """Isolate the exact-head guard from the approval refusal in E7."""
    tokens = {name: Path(getattr(args, name + "_token_file")).read_text().strip()
              for name in ("author", "approver", "other")}
    recorder = Recorder(args.base_url, tokens, args.output / "guard", "../../")
    call = recorder.request
    version = call("E7", "version", "GET", "/version", "anonymous", required=True)
    if version != {"version": "16.0.3+gitea-1.22.0"}:
        raise RuntimeError("this experiment requires exactly Forgejo 16.0.3")
    for actor in ("author", "approver"):
        user = call("E7", "user-" + actor, "GET", "/user", actor, required=True)
        if user["login"] != actor:
            raise RuntimeError(f"expected disposable login {actor}")
    repo = f"/repos/approver/{args.repository}"
    call("E7", "guard-branch", "POST", repo + "/contents/guard.txt", body={
        "branch": "main", "new_branch": "guard-probe", "message": "Isolate head guard",
        "content": base64.b64encode(b"Disposable guard probe\n").decode()}, required=True)
    pr = call("E7", "guard-pr", "POST", repo + "/pulls", body={
        "head": "guard-probe", "base": "main", "title": "E7 approved head guard",
        "body": "Disposable exact-head check after approval."}, required=True)
    pull = repo + f"/pulls/{pr['number']}"
    head = pr["head"]["sha"]
    call("E7", "guard-approval", "POST", pull + "/reviews", "approver", {
        "event": "APPROVED", "commit_id": head, "body": "Approve guard probe"},
        required=True)
    call("E7", "wrong-approved-head", "POST", pull + "/merge", body={
        "Do": "merge", "head_commit_id": "2" * 40,
        "delete_branch_after_merge": True})
    call("E7", "correct-approved-head", "POST", pull + "/merge", body={
        "Do": "merge", "head_commit_id": head, "delete_branch_after_merge": True})
    call("E7", "guard-merged-pr", "GET", pull)
    with (args.output / "README.md").open("a") as readme:
        readme.write("\nThe [E7 approved-head guard supplement](guard/README.md) "
                     "separates the head guard from the earlier approval refusal.\n")


def settled_reviews(args: argparse.Namespace) -> None:
    """Read flags again after the sequence; preserve timing-dependent results."""
    tokens = {name: Path(getattr(args, name + "_token_file")).read_text().strip()
              for name in ("author", "approver", "other")}
    recorder = Recorder(args.base_url, tokens, args.output / "settled", "../../")
    pull = f"/repos/approver/{args.repository}/pulls/1"
    recorder.request("E9", "settled-pr", "GET", pull)
    recorder.request("E9", "settled-reviews", "GET", pull + "/reviews")
    with (args.output / "README.md").open("a") as readme:
        readme.write("\nThe [later E9 snapshot](settled/README.md) preserves "
                     "the flags observed after the sequence.\n")


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--base-url", required=True)
    for actor in ("author", "approver", "other"):
        parser.add_argument(f"--{actor}-token-file", required=True, type=Path)
    parser.add_argument("--repository", default="issue54-review-api")
    parser.add_argument("--output", required=True, type=Path)
    parser.add_argument("--git-workdir", required=True, type=Path)
    parser.add_argument("--phase", choices=("full", "guard", "settled"), default="full")
    args = parser.parse_args()
    if not re.fullmatch(r"[a-z][a-z0-9-]{0,63}", args.repository):
        parser.error("repository must be a simple new disposable repository name")
    if args.phase == "guard":
        guard_probe(args)
    elif args.phase == "settled":
        settled_reviews(args)
    else:
        run(args)


if __name__ == "__main__":
    main()
